/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/identificacion` | `/identificacion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historial` | `/historial`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inicio` | `/inicio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reservar` | `/reservar`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/identificacion` | `/identificacion`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/historial` | `/historial`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/inicio` | `/inicio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reservar` | `/reservar`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/identificacion${`?${string}` | `#${string}` | ''}` | `/identificacion${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/historial${`?${string}` | `#${string}` | ''}` | `/historial${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/inicio${`?${string}` | `#${string}` | ''}` | `/inicio${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reservar${`?${string}` | `#${string}` | ''}` | `/reservar${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/identificacion` | `/identificacion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historial` | `/historial`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inicio` | `/inicio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reservar` | `/reservar`; params?: Router.UnknownInputParams; };
    }
  }
}
